services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5

  airflow-webserver:
    image: apache/airflow:2.8.1
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'True'
      PYTHONPATH: /opt/airflow
      _PIP_ADDITIONAL_REQUIREMENTS: "pymysql"
      AIRFLOW__API__AUTH_BACKEND: airflow.api.auth.backend.basic_auth
    volumes:
      - ./dags:/opt/airflow/dags
      - ./utils:/opt/airflow/utils
      - ./extract:/opt/airflow/extract
      - ./transform:/opt/airflow/transform
      - ./config:/opt/airflow/config
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./requirements.txt:/requirements.txt
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 20s
      timeout: 30s
      retries: 5

  airflow-scheduler:
    image: apache/airflow:2.8.1
    depends_on:
      airflow-webserver:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      PYTHONPATH: /opt/airflow
      _PIP_ADDITIONAL_REQUIREMENTS: "pymysql"
      AIRFLOW__API__AUTH_BACKEND: airflow.api.auth.backend.basic_auth
    volumes:
      - ./dags:/opt/airflow/dags
      - ./transform:/opt/airflow/transform
      - ./utils:/opt/airflow/utils
      - ./extract:/opt/airflow/extract
      - ./config:/opt/airflow/config
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./requirements.txt:/requirements.txt
    command: scheduler

volumes:
  postgres-db-volume: